apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80        # Port your app will be exposed on inside the cluster
      targetPort: 80   # Port your React app is listening on inside the container
      nodePort: 30000  # Port exposed on the node (can be any available port in the range 30000-32767)
  type: NodePort      # Change LoadBalancer to NodePort for local environments


