apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  labels:
    app: fastapi-app
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: fastapi-app
  type: LoadBalancer # Expose externally
